/work/UGE/8.0.1/hoffman2/spool/n7115/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6046/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6224/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6228/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6191/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6222/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6121/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6050/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7235/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6222/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7131/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7221/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6240/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6112/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7234/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7195/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6047/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7197/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6190/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6237/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6232/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6221/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7125/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6124/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7235/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7217/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6047/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7113/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7192/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6193/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7229/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6228/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6125/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6238/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7118/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7109/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6109/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7197/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6111/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6237/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6190/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7227/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6224/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6051/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6228/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6224/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6046/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6222/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7127/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7222/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7218/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6221/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7131/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7124/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7049/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7127/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7112/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n7221/job_scripts/2452499: line 21: syntax error: unexpected end of file
/work/UGE/8.0.1/hoffman2/spool/n6117/job_scripts/2452499: line 21: syntax error: unexpected end of file
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    fin_max_length = 0
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    fin_max_length = 0
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    fin_max_length = 0
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    fin_max_length = 0
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    fin_max_length = 0
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    fin_max_length = 0
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    max_hist = None
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    max_hist = None
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    max_hist = None
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 153, in <module>
    max_hist = None
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 129, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 104, in <module>
    draw_samples_fns = [draw_SAW_samples0,draw_SAW_samples1, draw_SAW_samples2]
NameError: name 'draw_SAW_samples2' is not defined
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 154, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 178, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 177, in <module>
    pickle.dump(max_hist,f)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 160, in <module>
    samples,fin_samples = draw_samples_fn(batch=batch)
  File "problem2.py", line 53, in draw_SAW_samples1
    samples.append(SAWSample(np.prod(px),saw.length, copy.deepcopy(saw.history)))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 292, in _reconstruct
    y = callable(*args)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copyreg.py", line 88, in __newobj__
    return cls.__new__(cls, *args)
  File "<string>", line 14, in __new__
MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "problem2.py", line 174, in <module>
    fin_writer.writerows(data)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 160, in <module>
    samples,fin_samples = draw_samples_fn(batch=batch)
  File "problem2.py", line 53, in draw_SAW_samples1
    samples.append(SAWSample(np.prod(px),saw.length, copy.deepcopy(saw.history)))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 293, in _reconstruct
    memo[id(x)] = y
MemoryError
/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copyreg.py", line 88, in __newobj__
    return cls.__new__(cls, *args)
  File "<string>", line 14, in __new__
MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "problem2.py", line 174, in <module>
    fin_writer.writerows(data)
MemoryError
py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 293, in _reconstruct
    memo[id(x)] = y
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 160, in <module>
    samples,fin_samples = draw_samples_fn(batch=batch)
  File "problem2.py", line 53, in draw_SAW_samples1
    samples.append(SAWSample(np.prod(px),saw.length, copy.deepcopy(saw.history)))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 293, in _reconstruct
    memo[id(x)] = y
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 160, in <module>
    samples,fin_samples = draw_samples_fn(batch=batch)
  File "problem2.py", line 53, in draw_SAW_samples1
    samples.append(SAWSample(np.prod(px),saw.length, copy.deepcopy(saw.history)))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 293, in _reconstruct
    memo[id(x)] = y
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 160, in <module>
    samples,fin_samples = draw_samples_fn(batch=batch)
  File "problem2.py", line 53, in draw_SAW_samples1
    samples.append(SAWSample(np.prod(px),saw.length, copy.deepcopy(saw.history)))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 293, in _reconstruct
    memo[id(x)] = y
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 160, in <module>
    samples,fin_samples = draw_samples_fn(batch=batch)
  File "problem2.py", line 53, in draw_SAW_samples1
    samples.append(SAWSample(np.prod(px),saw.length, copy.deepcopy(saw.history)))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 293, in _reconstruct
    memo[id(x)] = y
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 160, in <module>
    samples,fin_samples = draw_samples_fn(batch=batch)
  File "problem2.py", line 53, in draw_SAW_samples1
    samples.append(SAWSample(np.prod(px),saw.length, copy.deepcopy(saw.history)))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 293, in _reconstruct
    memo[id(x)] = y
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 160, in <module>
    samples,fin_samples = draw_samples_fn(batch=batch)
  File "problem2.py", line 53, in draw_SAW_samples1
    samples.append(SAWSample(np.prod(px),saw.length, copy.deepcopy(saw.history)))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 160, in <module>
    samples,fin_samples = draw_samples_fn(batch=batch)
  File "problem2.py", line 53, in draw_SAW_samples1
    samples.append(SAWSample(np.prod(px),saw.length, copy.deepcopy(saw.history)))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 187, in deepcopy
    _keep_alive(x, memo) # Make sure x lives at least as long as d
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 264, in _keep_alive
    memo[id(memo)].append(x)
MemoryError
Traceback (most recent call last):
  File "problem2.py", line 160, in <module>
    samples,fin_samples = draw_samples_fn(batch=batch)
  File "problem2.py", line 53, in draw_SAW_samples1
    samples.append(SAWSample(np.prod(px),saw.length, copy.deepcopy(saw.history)))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 293, in _reconstruct
    memo[id(x)] = y
MemoryError
50000
49000
Traceback (most recent call last):
  File "problem2.py", line 161, in <module>
    samples,fin_samples = draw_samples_fn(batch=batch)
  File "problem2.py", line 53, in draw_SAW_samples1
    samples.append(SAWSample(np.prod(px),saw.length, copy.copy(saw.history)))
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 77, in copy
    return copier(x)
  File "/u/local/apps/anaconda/python3-4.2.0/lib/python3.5/copy.py", line 126, in _copy_with_constructor
    return type(x)(x)
MemoryError
50000
49000
48000
47000
46000
45000
44000
43000
42000
41000
40000
39000
38000
37000
36000
35000
34000
33000
32000
31000
30000
29000
28000
27000
26000
25000
24000
23000
22000
21000
20000
19000
18000
17000
16000
15000
14000
13000
12000
11000
10000
9000
8000
7000
6000
5000
4000
3000
2000
1000
50000
49000
48000
47000
46000
45000
44000
43000
42000
41000
40000
39000
38000
37000
36000
35000
34000
33000
32000
31000
30000
29000
28000
27000
26000
25000
24000
23000
22000
21000
20000
19000
18000
17000
16000
15000
14000
13000
12000
11000
10000
9000
8000
7000
6000
5000
4000
3000
2000
1000
